### ISSUE TITLE
Debug cursor on caster?

### ISSUE THREAD

**Issue by ssbr** [aevyrie/bevy_mod_raycast#10]
When the raycast source isn't a camera, and you mess up where it's pointing, it would be useful to have a debug cursor on that source that points in the direction that it's casting.

**Comment by aevyrie** [comment]
This is a great idea @ssbr, I'm on board with adding this. If you or anyone else is interested in implementing it, it should be a pretty straightforward addition to the current debug cursor.

**Comment by aevyrie** [comment]
Examples of this are now in the repo.
