### ISSUE TITLE
Undocumented `DefaultRaycastingPlugin` vs. `DeferredRaycastingPlugin`

### ISSUE THREAD

**Issue by djeedai** [aevyrie/bevy_mod_raycast#105]
Hi,

I upgraded to 0.16 from an earlier version where I was using `DefaultRaycastingPlugin`, and nothing worked, the `RaycastSource` ray was always `None`. Turns out `build_rays()` was not called because I needed instead `DeferredRaycastingPlugin::<T>`. But this doesn't seem to be explained anywhere, and `DefaultRaycastingPlugin` is not documented either.

Switching to `DeferredRaycastingPlugin::<T>` instead solved everything. Maybe there should be some mention in the docs?

**Comment by aevyrie** [comment]
This was mentioned in the changeling for 0.15. There is also extensive documentation at the root of the crate explaining the two APIs and how to choose them: https://docs.rs/bevy_mod_raycast/latest/bevy_mod_raycast/

**Comment by djeedai** [comment]
I understand the difference between the two APIs, but I don't see any mention of `DefaultRaycastingPlugin` at the crate root, and I don't understand how that plugin is related to the choice of an API (since it's called "default").

**Comment by aevyrie** [comment]
Addressed with a rename and docs in 0.18.0-rc.0
