### ISSUE TITLE
conflict when accessing ResMut<Assets<Mesh>>

### ISSUE THREAD

**Issue by tricarbonate** [aevyrie/bevy_mod_raycast#106]
I have a ray cast system that spawns new meshes when the ray hits certain objects. But the Raycast accesses the meshes (with Res<Assets<Mesh>>), so it is not possible to use ResMut<Assets<Mesh>> in the same system because it would cause error B0002 (see [https://bevyengine.org/learn/errors/#b0002](https://bevyengine.org/learn/errors/#b0002))

I have a system that looks like this:
``` rust
pub fn chunk_deform_system(
    mut proc_entities: ResMut<ProcEntities>,
    camera: Query<&mut Transform, With<CameraComponent>>,
    mut raycast: Raycast, // meshes: &mut Assets<Mesh>,
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    mut time: ResMut<Time>,
    mut buttons: ResMut<Input<MouseButton>>,
) {
```
The access with mut meshes: ResMut<Assets<Mesh>> causes B0002 but I'm probably missing a better way of doing this

**Comment by aevyrie** [comment]
Yes, you need to read meshes to be able to raycast them, so you will need to split your system apart into smaller systems.
