### ISSUE TITLE
Shooting second ray depending on first ray's intersection point

### ISSUE THREAD

**Issue by AugustHolst** [aevyrie/bevy_mod_raycast#11]
Is this even possible with the current implementation? Do I even need the first ray to accomplish this?

I've a attached a little demo of my project to show what I currently have.
https://user-images.githubusercontent.com/34474922/117439102-b2ec7a80-af32-11eb-9686-bd134a2c2921.mp4
Essentially I'd like to shoot a ray from the player at where the screenspace ray intersects, but the ray's direction seems to not alter on the Y-axis as desired.

My code is here: https://github.com/AugustHolst/shooter/blob/974aeb2e239b203508f20e130bc7f8c78f94b5c2/src/main.rs
I instantiate my two ray cast sources on line 28 and 69 and try to set the desired ray's transform on line 121.

Also sorry if this is misuse of the 'Issues' system, it's my first time using it.

**Comment by aevyrie** [comment]
It looks like you are doing this correctly. I'd suggest debugging `shoot_dir` to see if the y component is changing when you move the mouse, it seems clear from the debug cursor that the mouse picking is intersecting correctly. My guess is this is a simple mistake in the math somewhere.

As an aside:

https://github.com/AugustHolst/shooter/blob/974aeb2e239b203508f20e130bc7f8c78f94b5c2/src/main.rs#L108

this line is setting the raycast source to the screenspace position, however this won't be updated until the next frame. The only issue is that you will have at least a frame of lag. I'd recommend copying this:

https://github.com/aevyrie/bevy_mod_raycast/blob/72532403cb42d1690eac1b274543b082b7d35f1b/examples/mouse_picking.rs#L21-L25

There is a dedicated system that updates the cursor position _before_ the raycasting system builds the rays and intersects them.

These lines show the same issue:

https://github.com/AugustHolst/shooter/blob/974aeb2e239b203508f20e130bc7f8c78f94b5c2/src/main.rs#L121-L122

You are setting up a ray to shoot from the player, but the result won't be ready until the next time the raycasting system is run! I'd recommend you make a separate system to handle all your ray cast source setup for the mouse and player, like:

`shooter::setup_rays` (NEW!) -> RaycastSystem::BuildRays -> RaycastSystem::UpdateRaycast -> `shooter::control_player`

> Also sorry if this is misuse of the 'Issues' system, it's my first time using it.

I'm happy to help, and this is an appropriate place to post, especially if you think something in this plugin isn't working! For a faster response, I'd recommend posting in the Bevy discord #help channel, and someone (including me) might see it sooner to help you out.
