### ISSUE TITLE
Adding an IgnoreRaycasts Marker component

### ISSUE THREAD

**Issue by Sigma-dev** [aevyrie/bevy_mod_raycast#123]
Hey, there is probably a good reason for why it doesn't exist, but to me it seems lke an IgnoreRaycasts marker component would be pretty useful and not that hard to add right ?

Right now the best alternative I know off is to use the with_filter capabilities, which is a slight inconvenience.

**Comment by aevyrie** [comment]
This crate is end-of-life and has been upstreamed to bevy.

If you are using the immediate `Raycast` system param, then using `with_filter` is how you would add a filter.
If you want opt-in raycasting with components, you can use the deferred raycaster.
