### ISSUE TITLE
Support meshes without indices

### ISSUE THREAD

**Issue by jakobhellermann** [aevyrie/bevy_mod_raycast#13]
When a mesh without indices set is in the scene, `bevy_mod_raycast` panics at `No index matrix found in mesh WeakHandle<Mesh>`.

**Comment by aevyrie** [comment]
What is the proper way to handle a mesh without indices?

- read the vertex list directly
- generate an error, this is an invalid state
- something else?

**Comment by jakobhellermann** [comment]
I would say read the vertex list directly.
Instead of iterating over the indices and using the referenced vertices, you could iterate the vertices directly in chunks of 3.

**Comment by aevyrie** [comment]
@jakobhellermann this should now be working. Let me know if you still have issues.
