### ISSUE TITLE
Support casting a ray from screenspace to a specified set of geometry

### ISSUE THREAD

**Issue by twitchyliquid64** [aevyrie/bevy_mod_raycast#2]
I'm in the process of implementing a 3d translation gizmo, and looking to use `bevy_mod_raycast` to compute the translation delta for when a gizmo axis is dragged.

![image](https://user-images.githubusercontent.com/6328589/106080694-72c46300-60cc-11eb-8c10-930eaed04520.png)

Could support be added to intersect a mouse position (or any screenspace position) with a fixed set of geometry or meshes, and return the point of intersection? In my case, I would like to intersect screenspace with a plane aligned to the axis being dragged.

**Comment by aevyrie** [comment]
As a starting point, what if this only allowed ray casting from screenspace to a primitive in world space?

**Comment by twitchyliquid64** [comment]
That would work for me! :)

**Comment by aevyrie** [comment]
I've pushed something you can test out to master. 🙂 

`RayCastSource<T>` now has the function:
```rust
pub fn intersect_primitive(&self, shape: Primitive3d) -> Option<Intersection>
```

You can specify primitives with `Primitive3d`:

```rust
pub enum Primitive3d {
    ///Sphere{ radius: f32, position: Vec3 },
    Plane { point: Vec3, normal: Vec3 },
}
```

The only primitive enabled right now is a plane defined by a point and normal. Let me know if this works, I haven't even tested it yet!

**Comment by twitchyliquid64** [comment]
Close!

```
error: cannot construct `Primitive3d` with struct literal syntax due to inaccessible fields
  --> src/selection.rs:76:57
   |
76 |             println!("{:?}", source.intersect_primitive(Primitive3d::Plane{
   |                                                         ^^^^^^^^^^^^^^^^^^
```

**Comment by twitchyliquid64** [comment]
Oof nvm that error goes away if i specify all the fields lel sorry

**Comment by twitchyliquid64** [comment]
I cant get it working :/ its always returning `None`, even if I plumb in `point = (0,0,0)` and any standard normal (ie: (0,0,1)) :(

**Comment by twitchyliquid64** [comment]
Also I'm not sure if this is because I'm using the 0.4 bevy but yous are on the master branch, but I have to convert my `Vec2` & `Vec3` types to use them in `bevy_mod_raycast`.

**Comment by aevyrie** [comment]
I was hoping I could be lazy and my math would be right without testing. Serves me right. 😆

**Comment by aevyrie** [comment]
> Also I'm not sure if this is because I'm using the 0.4 bevy but yous are on the master branch, but I have to convert my `Vec2` & `Vec3` types to use them in `bevy_mod_raycast`.

Yeah, I'm working on master to prep for the next update.

**Comment by aevyrie** [comment]
You need to reference a picking source you've grabbed from a query. This is needed because the picking source uses a system to grab the window and camera information. Instantiating it like you have here won't work because the source is never initialized. I might need to rethink how that works.

**Comment by twitchyliquid64** [comment]
Thanks!

I've confirmed this works using the new `RayCastSource::with_screenspace_ray` method.
