### ISSUE TITLE
Doesn't work for WASM due to the rayon dependency

### ISSUE THREAD

**Issue by mvlabat** [aevyrie/bevy_mod_raycast#32]
Hi! Thank you for maintaining this crate.

I'm using `bevy_mod_raycast` in my WASM pet project, and after updating to 0.3 my project stopped working.

> panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Error { kind: Unsupported, message: "operation not supported on this platform" }) }'

I believe `rayon` dependency should be optional and enabled only for non-WASM targets.

**Comment by aevyrie** [comment]
> I believe `rayon` dependency should be optional and enabled only for non-WASM targets.

I'll put this behind a feature flag ASAP.

**Comment by aevyrie** [comment]
I've removed rayon completely and replaced it with a parallel query after finding it made no perf difference. Pushing 0.3.3 to crates now.

**Comment by aevyrie** [comment]
Released!

**Comment by mvlabat** [comment]
Cheers!
