### ISSUE TITLE
Only back faces are selected with an orthographic camera.

### ISSUE THREAD

**Issue by BenCantCode** [aevyrie/bevy_mod_raycast#33]
Using a perspective camera in the mouse_picking example, the debug cursor points towards the camera when the sphere is hovered over. Using an orthographic camera (`OrthographicCameraBundle::new_3d()`), the cursor is instead placed on the side facing away from the camera. Here's a screenshot of what this looks like:

<img width="652" alt="Screen Shot 2022-01-16 at 4 51 37 PM" src="https://user-images.githubusercontent.com/11827561/149685215-1987201a-7168-48c8-adf0-10a9a2ee2ebf.png">

This issue also seems to affect bevy_mod_picking.

**Comment by aevyrie** [comment]
Thanks for the report. I'll take a look.
