### ISSUE TITLE
No more working picking if camera is translated

### ISSUE THREAD

**Issue by pjalaber** [aevyrie/bevy_mod_raycast#37]
Apply the linked patch that translates the camera on mouse_picking example.
It seems picking does not work anymore.
https://gist.github.com/pjalaber/f43979121cad518cbcb95e960a70678a

**Comment by aevyrie** [comment]
Yes, I've been trying to fix a number of edge cases that were causing more regressions. This should be fixed in the version I just pushed and published to crates.io.
