### ISSUE TITLE
Intersection API suggestion

### ISSUE THREAD

**Issue by Shatur** [aevyrie/bevy_mod_raycast#60]
**Problem description**

Currently intersection inserted into a separate entity:

https://github.com/aevyrie/bevy_mod_raycast/blob/5949fc7f021e6900c3d14b4e6f22ef4426489441/src/lib.rs#L517-L519

But this behavior is not very expected. In a game with menu, users will need to remove such entities manually when exiting a game session. And since the `Intersection` component is added to a new entity, users do not have access to information about which entity was intersected (they have to use `RayCastSource::intersect_list()`), which makes this component not very useful.

**Suggestion**

I would suggest to just remove `Intersection` component and its system at all since this information already available in `RayCastSource` to avoid needless synchronization and duplication.

**Comment by Fincap** [comment]
I agree with this suggestion, the way that the API comments and examples are structured indicates that the `Intersection` component is added to the entity collided with, and not to a brand new entity which has, at least for me, led to a lot of confusion until I finally had to go in and pick apart the source function.

At the very least, the documentation surrounding this component should be amended to clarify this.

**Comment by aevyrie** [comment]
The `Intersection` component has been removed as the ownership was not clear. Instead, intersections are available on both the `RaycastMesh` and `RaycastSource`.
