### ISSUE TITLE
Update to Bevy 0.9

### ISSUE THREAD

**Issue by olegomon** [aevyrie/bevy_mod_raycast#63]
## Summary

As of today Bevy is 2 open issues behind the 0.9 milestone. See: https://github.com/bevyengine/bevy/milestone/7 and this crate should support it asap ;)

**Bevy Migration**
- remove deprecated API usage of `spawn_bundle()` and use `spawn()` instead

**Comment by olegomon** [comment]
@aevyrie I prepared a small PR which updates some of the deprecated Bevy APIs. Let me know if that's ok, any feedback appreciated. 

https://github.com/aevyrie/bevy_mod_raycast/pull/64

**Comment by aevyrie** [comment]
Completed. Thank you!
