### ISSUE TITLE
`RayCastMesh` should be type-registered for use in `Scene`

### ISSUE THREAD

**Issue by djeedai** [aevyrie/bevy_mod_raycast#65]
I have a scene that I want to serialize/deserialize, containing meshes that I'd like marked with `RayCastMesh`. However this doesn't seem to be possible unless `RayCastMesh` is registered with the type system. Would it be possible to add this? `RayCastSource` is probably another good candidate too.

**Comment by aevyrie** [comment]
This is blocked on https://github.com/bevyengine/bevy/issues/5144.

**Comment by aevyrie** [comment]
Looks like
```rs
bevy::reflect::impl_reflect_value!(RaycastMesh<T: Reflect + Clone>);
bevy::reflect::impl_from_reflect_value!(RaycastMesh<T: Reflect + Clone>);
```
should do the trick, but I want to see if I can minimize breakage for people that don't need reflection.

**Comment by aevyrie** [comment]
@djeedai can you please give #67 a try and let me know if this works?

**Comment by djeedai** [comment]
#67 depends on Bevy 0.9, it will take at very least a week before all crates I need upgraded.

**Comment by aevyrie** [comment]
This has been implemented and released.
