### ISSUE TITLE
Replace Ray3d with bevy::prelude::Ray

### ISSUE THREAD

**Issue by Shatur** [aevyrie/bevy_mod_raycast#68]
After 0.9 Bevy [have this functionality built-in](https://bevyengine.org/news/bevy-0-9/#camera-viewport-to-world).

**Comment by TotalKrill** [comment]
Yeah, but the built in Ray functionality in Bevy, is not as complete as this from what I can tell, I also does not use Vec3A types, which are SIMD compatible, and thus the Ray3D *Should* be more performant

**Comment by Shatur** [comment]
Fair.
