### ISSUE TITLE
Adding simple primitives

### ISSUE THREAD

**Issue by ValorZard** [aevyrie/bevy_mod_raycast#8]
2d: Circle, Box, Capsule
3d: Sphere, Cube/box, Capsule

Additionally, it would be nice if they could rotate and stuff, and if it would be possible for these shapes to merge. This would allow for a basic collision system to be formed.

**Comment by ValorZard** [comment]
Also, a way to display these collision primitive would be nice as well

**Comment by aevyrie** [comment]
I think visualization is better left to another crate, but it sounds like you are looking for the ability to raycast against these primitives to find the intersection?

Do you think parry would be a better fit for what you're trying to do? https://github.com/dimforge/parry

Is this what you're thinking for viz (animation)?: https://github.com/aevyrie/bevy_mod_bounding
