### ISSUE TITLE
Panic with bevy master cf221f96

### ISSUE THREAD

**Issue by edisno** [aevyrie/bevy_mod_raycast#9]
thread 'main' panicked at '$state_name<bevy_mod_raycast::bounding::BoundVol> conflicts with a previous access in this query. Shared access cannot coincide with exclusive access.'

I believe this bevy commit introduced the problem: https://github.com/bevyengine/bevy/commit/9657f58f6a84b82f508cf5f09765db3d26d139ff

**Comment by aevyrie** [comment]
Can you provide more details from the error? Are you sure this isn't coming from your own systems?

**Comment by aevyrie** [comment]
This is fixed in `master` fyi.
