### ISSUE TITLE
ERROR raycast: bevy_mod_raycast: Invalid intersection check: `TriangleList` is the only supported `PrimitiveTopology`

### ISSUE THREAD

**Issue by zzhgithub** [aevyrie/bevy_mod_raycast#90]
when I update to new version. this happened and not cast with 'Set'? how to fix it

**Comment by aevyrie** [comment]
This behavior has not changed in a long time: https://github.com/aevyrie/bevy_mod_raycast/blame/424e0f0c1dcb47d759428902086727faa7a6f79e/src/lib.rs#L554

Raycasting only works for TriangleList meshes. See the bevy mesh docs: https://docs.rs/bevy/latest/bevy/render/mesh/enum.PrimitiveTopology.html
